### ISSUE TITLE
Авторизация

### ISSUE THREAD

**Issue by GoldenLs** [Gml-Launcher/Gml.Backend#94]
Установилось запустилось все ок , но при регистрации лезет ошибка 
![2024-10-30_16-38-04](https://github.com/user-attachments/assets/25109aab-7b61-4870-bb51-ce15727c303d)

**Comment by GamerVII-NET** [comment]
Что у вас указано в frontend/Gml.Web.Client/.env файле?

**Comment by GoldenLs** [comment]
![image](https://github.com/user-attachments/assets/c3d4071b-4bcb-4c1d-9c1f-9b63453b3554)

**Comment by Arsenii1109** [comment]
Ты в начале http:// не указал и в конце порт :5000 . У тебя должно вот так выглядеть http://192.168.100.159:5000

И тогда у тебя должно все заработать

**Comment by GoldenLs** [comment]
спасибо

**Comment by GoldenLs** [comment]
Проверил, с исправленным .env . Переустановил полностью результата нет.

**Comment by Scrurk** [comment]
Покажи обновлённый frontend/Gml.Web.Client/.env

**Comment by GamerVII-NET** [comment]
1) Заполни frontend/Gml.Web.Client/.env

```
NEXT_PUBLIC_BASE_URL=http://192.168.100.159:5000/
NEXT_PUBLIC_PREFIX_API=api
NEXT_PUBLIC_VERSION_API=v1
```
2) Запусти скрипт обновления 
```
curl -s https://raw.githubusercontent.com/GamerVII-NET/Gml.Backend.Installer/master/gml-updater-rus.sh | sh
```

**Comment by GoldenLs** [comment]
![image](https://github.com/user-attachments/assets/52eb01a8-7a1d-47fe-98da-0df5adcf13ef)
![image](https://github.com/user-attachments/assets/cb543852-bdff-46a2-a5aa-226299e67dcc)
![image](https://github.com/user-attachments/assets/20d0378a-bc2b-45a7-8eeb-3aa847e9a739)
![image](https://github.com/user-attachments/assets/9b2783a1-d0e3-49ca-bf85-6b12f9df8752)

Все также просто не могу зарегатся.

**Comment by gamerviihub** [comment]
Убери слеш вконце. В адресе 5000

NEXT_PUBLIC_BASE_URL=http://192.168.100.159:5000
NEXT_PUBLIC_PREFIX_API=api
NEXT_PUBLIC_VERSION_API=v1

**Comment by GoldenLs** [comment]
Убрал слеш. Не регается. Обновил не регается. Оставил пункт почты пустым ,зарегался.

**Comment by GoldenLs** [comment]
Спасибо всем за помощь. Почему та именно мою почту он не регает.

**Comment by GamerVII-NET** [comment]
Не за что, удачи в развитии проекта)
